export const ACTIONS = {
  ADD_HASHTAG: "ADD_HASHTAG",
  ADD_TO_LIST: "ADD_TO_LIST",
  GET_SESSION_DATA: "GET_SESSION_DATA",
  ITEM_COMPLETED: "ITEM_COMPLETED",
  NOT_COMPLETED: "NOT_COMPLETED",
  REMOVE_HASHTAGS: "REMOVE_HASHTAGS",
  RESET_TO_DO_LIST: "RESET_TO_DO_LIST",
  SEARCHED_TODO_COMPLETED: "SEARCHED_TODO_COMPLETED",
  SEARCHED_TODO_NOT_COMPLETED: "SEARCHED_TODO_NOT_COMPLETED",
};
